name: k_social_example
description: Demonstrates how to use the k_social plugin.

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  k_social:
    path: ../
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  cached_network_image: ^3.3.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
